package com.mycompany.practica_4_neatbeans;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Mesa extends javax.swing.JFrame {

    private ArrayList<JPanel> panelesZonasJugadores;
    private ArrayList<JLabel> labelsDeJugadores;
    private ArrayList<ArrayList<JButton>> botonesJugadores;

    public Mesa() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        pack();

        // Inicializar paneles para las cartas de los jugadores
        panelesZonasJugadores = new ArrayList<>();
        panelesZonasJugadores.add(zona_Jugador1);
        panelesZonasJugadores.add(zona_Jugador2);
        panelesZonasJugadores.add(zona_Jugador3);
        panelesZonasJugadores.add(zona_Jugador4);

        labelsDeJugadores = new ArrayList<>();
        labelsDeJugadores.add(nombreJugador1);
        labelsDeJugadores.add(nombreJugador2);
        labelsDeJugadores.add(nombreJugador3);
        labelsDeJugadores.add(nombreJugador4);

        botonesJugadores = new ArrayList<>();
        botonesJugadores.add(new ArrayList<>(List.of(ponerCarta1_Jugador1, ponerCarta2_Jugador1, ponerCarta3_Jugador1, ponerCarta4_Jugador1, ponerCarta5_Jugador1)));
        botonesJugadores.add(new ArrayList<>(List.of(ponerCarta1_Jugador2, ponerCarta2_Jugador2, ponerCarta3_Jugador2, ponerCarta4_Jugador2, ponerCarta5_Jugador2)));
        botonesJugadores.add(new ArrayList<>(List.of(ponerCarta1_Jugador3, ponerCarta2_Jugador3, ponerCarta3_Jugador3, ponerCarta4_Jugador3, ponerCarta5_Jugador3)));
        botonesJugadores.add(new ArrayList<>(List.of(ponerCarta1_Jugador4, ponerCarta2_Jugador4, ponerCarta3_Jugador4, ponerCarta4_Jugador4, ponerCarta5_Jugador4)));
    }

    public void mostrarCartasJugadores(ArrayList<Jugador> jugadores) {
        for (JPanel zonaJugador : panelesZonasJugadores) {
            zonaJugador.removeAll();
            zonaJugador.setVisible(false);
        }

        for (JLabel nombreJugador : labelsDeJugadores) {
            nombreJugador.setVisible(false);
        }

        // Ocultar los botones de los jugadores que no juegan
        for (ArrayList<JButton> botones : botonesJugadores) {
            for (JButton boton : botones) {
                boton.setVisible(false);
            }
        }

        for (int i = 0; i < jugadores.size(); i++) {
            Jugador jugador = jugadores.get(i);
            JPanel zonaJugador = panelesZonasJugadores.get(i);
            JLabel nombreJugador = labelsDeJugadores.get(i);
            ArrayList<JButton> botonesJugador = botonesJugadores.get(i);

            zonaJugador.setVisible(true);
            nombreJugador.setVisible(true);

            // Hacer visibles los botones de este jugador
            for (JButton boton : botonesJugador) {
                boton.setVisible(true);
            }

            for (int j = 0; j < jugador.getManoSize(); j++) {
                VistaCarta vistaCarta = new VistaCarta(jugador.getCarta(j),this);
                zonaJugador.add(vistaCarta);
            }
            zonaJugador.revalidate();
            zonaJugador.repaint();
        }
    }

    public void actualizarTurno(int jugadorActual) {
        // Desactivar todos los botones
        for (ArrayList<JButton> botones : botonesJugadores) {
            for (JButton boton : botones) {
                boton.setEnabled(false);
            }
        }

        // Activar los botones solo para el jugador que tiene el turno
        ArrayList<JButton> botonesJugadorActual = botonesJugadores.get(jugadorActual);
        for (JButton boton : botonesJugadorActual) {
            boton.setEnabled(true);
        }
    }

    public void mostrarGanador(int jugadorGanador) {
        // Mostrar mensaje indicando el ganador
        JOptionPane.showMessageDialog(this, "¡El ganador es: " + labelsDeJugadores.get(jugadorGanador).getText() + "!");
    }

    public void moverCartaAJugadas(VistaCarta vistaCarta) {
        cartasJugadas.removeAll();
        JPanel zonaJugador = (JPanel) vistaCarta.getParent();
        zonaJugador.remove(vistaCarta);

        // Agregar la carta al panel de cartas jugadas
        cartasJugadas.add(vistaCarta);
        
        zonaJugador.revalidate();
        zonaJugador.repaint();

        // Actualizar la interfaz para mostrar la carta en el panel de cartas jugadas
        cartasJugadas.revalidate();
        cartasJugadas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        zona_Jugador1 = new javax.swing.JPanel();
        zona_Jugador2 = new javax.swing.JPanel();
        nombreJugador2 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        zona_Jugador3 = new javax.swing.JPanel();
        zona_Jugador4 = new javax.swing.JPanel();
        cartasJugadas = new javax.swing.JPanel();
        ponerCarta1_Jugador1 = new javax.swing.JButton();
        ponerCarta2_Jugador1 = new javax.swing.JButton();
        ponerCarta3_Jugador1 = new javax.swing.JButton();
        ponerCarta4_Jugador1 = new javax.swing.JButton();
        ponerCarta5_Jugador1 = new javax.swing.JButton();
        ponerCarta1_Jugador2 = new javax.swing.JButton();
        ponerCarta2_Jugador2 = new javax.swing.JButton();
        ponerCarta3_Jugador2 = new javax.swing.JButton();
        ponerCarta4_Jugador2 = new javax.swing.JButton();
        ponerCarta5_Jugador2 = new javax.swing.JButton();
        ponerCarta1_Jugador3 = new javax.swing.JButton();
        ponerCarta2_Jugador3 = new javax.swing.JButton();
        ponerCarta3_Jugador3 = new javax.swing.JButton();
        ponerCarta4_Jugador3 = new javax.swing.JButton();
        ponerCarta5_Jugador3 = new javax.swing.JButton();
        ponerCarta1_Jugador4 = new javax.swing.JButton();
        ponerCarta2_Jugador4 = new javax.swing.JButton();
        ponerCarta3_Jugador4 = new javax.swing.JButton();
        ponerCarta4_Jugador4 = new javax.swing.JButton();
        ponerCarta5_Jugador4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanel1.setBackground(new java.awt.Color(161, 130, 98));
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 780));

        zona_Jugador1.setBackground(new java.awt.Color(161, 130, 98));
        zona_Jugador1.setLayout(new java.awt.GridLayout(1, 5, 3, 0));

        zona_Jugador2.setBackground(new java.awt.Color(161, 130, 98));
        zona_Jugador2.setLayout(new java.awt.GridLayout(5, 1, 0, 3));

        nombreJugador2.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        nombreJugador2.setForeground(new java.awt.Color(255, 200, 255));
        nombreJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador2.setText("Jugador 2");
        nombreJugador2.setPreferredSize(new java.awt.Dimension(170, 40));

        nombreJugador3.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        nombreJugador3.setForeground(new java.awt.Color(180, 232, 255));
        nombreJugador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador3.setText("Jugador 3");
        nombreJugador3.setPreferredSize(new java.awt.Dimension(170, 40));

        nombreJugador1.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        nombreJugador1.setForeground(new java.awt.Color(180, 232, 255));
        nombreJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador1.setText("Jugador 1");
        nombreJugador1.setPreferredSize(new java.awt.Dimension(170, 40));

        nombreJugador4.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        nombreJugador4.setForeground(new java.awt.Color(180, 232, 255));
        nombreJugador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJugador4.setText("Jugador 4");
        nombreJugador4.setPreferredSize(new java.awt.Dimension(170, 40));

        zona_Jugador3.setBackground(new java.awt.Color(161, 130, 98));
        zona_Jugador3.setLayout(new java.awt.GridLayout(1, 5, 0, 3));

        zona_Jugador4.setBackground(new java.awt.Color(161, 130, 98));
        zona_Jugador4.setPreferredSize(new java.awt.Dimension(250, 545));
        zona_Jugador4.setLayout(new java.awt.GridLayout(5, 1, 0, 3));

        cartasJugadas.setMinimumSize(new java.awt.Dimension(100, 130));

        ponerCarta1_Jugador1.setText("Poner");
        ponerCarta1_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta1_Jugador1ActionPerformed(evt);
            }
        });

        ponerCarta2_Jugador1.setText("Poner");
        ponerCarta2_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta2_Jugador1ActionPerformed(evt);
            }
        });

        ponerCarta3_Jugador1.setText("Poner");
        ponerCarta3_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta3_Jugador1ActionPerformed(evt);
            }
        });

        ponerCarta4_Jugador1.setText("Poner");
        ponerCarta4_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta4_Jugador1ActionPerformed(evt);
            }
        });

        ponerCarta5_Jugador1.setText("Poner");
        ponerCarta5_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta5_Jugador1ActionPerformed(evt);
            }
        });

        ponerCarta1_Jugador2.setText("Poner");
        ponerCarta1_Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta1_Jugador2ActionPerformed(evt);
            }
        });

        ponerCarta2_Jugador2.setText("Poner");

        ponerCarta3_Jugador2.setText("Poner");

        ponerCarta4_Jugador2.setText("Poner");
        ponerCarta4_Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta4_Jugador2ActionPerformed(evt);
            }
        });

        ponerCarta5_Jugador2.setText("Poner");

        ponerCarta1_Jugador3.setText("Poner");

        ponerCarta2_Jugador3.setText("Poner");
        ponerCarta2_Jugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta2_Jugador3ActionPerformed(evt);
            }
        });

        ponerCarta3_Jugador3.setText("Poner");

        ponerCarta4_Jugador3.setText("Poner");

        ponerCarta5_Jugador3.setText("Poner");
        ponerCarta5_Jugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCarta5_Jugador3ActionPerformed(evt);
            }
        });

        ponerCarta1_Jugador4.setText("Poner");

        ponerCarta2_Jugador4.setText("Poner");

        ponerCarta3_Jugador4.setText("Poner");

        ponerCarta4_Jugador4.setText("Poner");

        ponerCarta5_Jugador4.setText("Poner");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(nombreJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ponerCarta5_Jugador4)
                            .addComponent(ponerCarta1_Jugador4)
                            .addComponent(ponerCarta2_Jugador4)
                            .addComponent(ponerCarta3_Jugador4)
                            .addComponent(ponerCarta4_Jugador4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zona_Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(nombreJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zona_Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(ponerCarta1_Jugador3)
                                        .addGap(26, 26, 26)
                                        .addComponent(ponerCarta2_Jugador3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ponerCarta3_Jugador3)
                                        .addGap(28, 28, 28)
                                        .addComponent(ponerCarta4_Jugador3)
                                        .addGap(32, 32, 32)
                                        .addComponent(ponerCarta5_Jugador3)
                                        .addGap(22, 22, 22)))
                                .addGap(182, 182, 182))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(zona_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(271, 271, 271)
                                        .addComponent(cartasJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(zona_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ponerCarta1_Jugador2)
                                    .addComponent(ponerCarta2_Jugador2)
                                    .addComponent(ponerCarta3_Jugador2)
                                    .addComponent(ponerCarta4_Jugador2)
                                    .addComponent(ponerCarta5_Jugador2))))
                        .addGap(234, 234, 234))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(ponerCarta1_Jugador1)
                        .addGap(35, 35, 35)
                        .addComponent(ponerCarta2_Jugador1)
                        .addGap(35, 35, 35)
                        .addComponent(ponerCarta3_Jugador1)
                        .addGap(35, 35, 35)
                        .addComponent(ponerCarta4_Jugador1)
                        .addGap(35, 35, 35)
                        .addComponent(ponerCarta5_Jugador1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zona_Jugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(ponerCarta1_Jugador2)
                        .addGap(104, 104, 104)
                        .addComponent(ponerCarta2_Jugador2)
                        .addGap(102, 102, 102)
                        .addComponent(ponerCarta3_Jugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ponerCarta4_Jugador2)
                        .addGap(103, 103, 103)
                        .addComponent(ponerCarta5_Jugador2)
                        .addGap(54, 54, 54)))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(ponerCarta1_Jugador4)
                        .addGap(91, 91, 91)
                        .addComponent(ponerCarta2_Jugador4)
                        .addGap(97, 97, 97)
                        .addComponent(ponerCarta3_Jugador4)
                        .addGap(104, 104, 104)
                        .addComponent(ponerCarta4_Jugador4)
                        .addGap(101, 101, 101)
                        .addComponent(ponerCarta5_Jugador4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zona_Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zona_Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponerCarta1_Jugador3)
                    .addComponent(ponerCarta2_Jugador3)
                    .addComponent(ponerCarta3_Jugador3)
                    .addComponent(ponerCarta4_Jugador3)
                    .addComponent(ponerCarta5_Jugador3))
                .addGap(117, 117, 117)
                .addComponent(cartasJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zona_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponerCarta1_Jugador1)
                    .addComponent(ponerCarta2_Jugador1)
                    .addComponent(ponerCarta3_Jugador1)
                    .addComponent(ponerCarta4_Jugador1)
                    .addComponent(ponerCarta5_Jugador1))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ponerCarta2_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta2_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta2_Jugador1ActionPerformed

    private void ponerCarta1_Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta1_Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta1_Jugador2ActionPerformed

    private void ponerCarta4_Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta4_Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta4_Jugador2ActionPerformed

    private void ponerCarta2_Jugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta2_Jugador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta2_Jugador3ActionPerformed

    private void ponerCarta5_Jugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta5_Jugador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta5_Jugador3ActionPerformed

    private void ponerCarta1_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta1_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta1_Jugador1ActionPerformed

    private void ponerCarta3_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta3_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta3_Jugador1ActionPerformed

    private void ponerCarta4_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta4_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta4_Jugador1ActionPerformed

    private void ponerCarta5_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCarta5_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerCarta5_Jugador1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartasJugadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JButton ponerCarta1_Jugador1;
    private javax.swing.JButton ponerCarta1_Jugador2;
    private javax.swing.JButton ponerCarta1_Jugador3;
    private javax.swing.JButton ponerCarta1_Jugador4;
    private javax.swing.JButton ponerCarta2_Jugador1;
    private javax.swing.JButton ponerCarta2_Jugador2;
    private javax.swing.JButton ponerCarta2_Jugador3;
    private javax.swing.JButton ponerCarta2_Jugador4;
    private javax.swing.JButton ponerCarta3_Jugador1;
    private javax.swing.JButton ponerCarta3_Jugador2;
    private javax.swing.JButton ponerCarta3_Jugador3;
    private javax.swing.JButton ponerCarta3_Jugador4;
    private javax.swing.JButton ponerCarta4_Jugador1;
    private javax.swing.JButton ponerCarta4_Jugador2;
    private javax.swing.JButton ponerCarta4_Jugador3;
    private javax.swing.JButton ponerCarta4_Jugador4;
    private javax.swing.JButton ponerCarta5_Jugador1;
    private javax.swing.JButton ponerCarta5_Jugador2;
    private javax.swing.JButton ponerCarta5_Jugador3;
    private javax.swing.JButton ponerCarta5_Jugador4;
    private javax.swing.JPanel zona_Jugador1;
    private javax.swing.JPanel zona_Jugador2;
    private javax.swing.JPanel zona_Jugador3;
    private javax.swing.JPanel zona_Jugador4;
    // End of variables declaration//GEN-END:variables
}
