package com.mycompany.practica_4_neatbeans;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayson
 */
public class VistaCarta extends javax.swing.JPanel {

    private CartaLogica carta;
    private boolean volteada;

    public VistaCarta(CartaLogica carta) {
        this.carta = carta;
        this.volteada = true;
        initComponents();
        // Escucha cuando el componente se redimensiona
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                cargarImagen();
            }
        });
    }

    public CartaLogica getCarta() {
        return carta;
    }

    public void setCarta(CartaLogica carta) {
        this.carta = carta;
        cargarImagen();
    }

    public void voltearCarta() {
        volteada = !volteada; // Cambia el estado de la carta (de visible a volteada o viceversa)
        cargarImagen(); // Recargar la imagen dependiendo de si está volteada o no
    }

    public void cargarImagen() {
        String rutaImagen;
        // Define la ruta externa aquí (puedes permitir que se pase como argumento)
        if (volteada) {
            rutaImagen = "C:\\Users\\Jayson\\Desktop\\UABC\\Semestre 2024-2\\Programación Orientada a Objetos\\Laboratorio\\Codigo_Practicas\\Practica_4_Neatbeans\\src\\main\\java\\resources\\imagen" + carta.getValue() + "_" + carta.getSuit() + ".png";
        } else {
            rutaImagen = "C:\\Users\\Jayson\\Desktop\\UABC\\Semestre 2024-2\\Programación Orientada a Objetos\\Laboratorio\\Codigo_Practicas\\Practica_4_Neatbeans\\src\\main\\java\\resources\\carta_Volteada.png";
        }
        
        File archivoImagen = new File(rutaImagen);

        if (archivoImagen.exists()) {
            ImageIcon imagenIcono = new ImageIcon(rutaImagen);
            Image imagen = imagenIcono.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imagen));
        } else {
            JOptionPane.showMessageDialog(this, "Imagen no encontrada: " + rutaImagen, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 130));
        setPreferredSize(new java.awt.Dimension(100, 130));

        jPanel1.setBackground(new java.awt.Color(161, 130, 98));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 130));

        jLabel1.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 130));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
